---
title: "Prediction of general consumption"
output: html_document
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE,comment='')
```

```{r}
library(tsfa)
library(nFactors)
library(vars)
library(lubridate)
load('tabla_festivos.RData')
```


## Idea of app

The next application show the performance of the forecast algorithm studied. You can 


```{r}
# read data
# load(...)


 inputPanel(
  sliderInput("Size", label = "Days to predict", min=1,max=60,value=30),
  actionButton("Plot", "Try prediction")
              )

# Doesn't work:

  renderPlot({
    input$Plot

    
    # Use isolate() to avoid dependency on input$n

    isolate({
     
      {
  ## function bucle
  j<-1
  
  #dif = input$Size
  dif = 30
  param = 364 - dif
  datos=matrix(news$`General [kWh]`,nrow=param,ncol=96, byrow = T)
  predicc=matrix(news$`General [kWh]`[-c(1:(param*96))],nrow=dif,ncol=96, byrow = T)
  
  optnf=nBartlett(cor(datos),N = ncol(datos), alpha=0.05, cor=TRUE, details=TRUE, correction=TRUE)
  nf=optnf$nFactors[1]
  
  
  ##domingos y festivos
  valdom=ifelse(weekdays((news$Date))=="domingo",1,0)
  datdom=matrix(valdom,nrow = param,ncol = 96,byrow = T)[,1]
  preddom=matrix(valdom[-c(1:(param*96))],nrow=dif,ncol=96, byrow = T)[,1]
  
  ##festivos y fiestas navidad y sem santa
  festiusdat=matrix(news$festivo,nrow = param,ncol = 96,byrow = T)[,1]
  festiuspred=matrix(news$festivo[-c(1:(param*96))],nrow=dif,ncol=96, byrow = T)[,1]
  
  hwfiesdat=matrix(news$holw,nrow=param,ncol=96, byrow = T)[,1]
  hwfiespred=matrix(news$holw[-c(1:(param*96))],nrow=dif,ncol=96, byrow = T)[,1]
  
  datos2 <- datos
  datdom2<-datdom
  fest2 <- festiusdat
  nad2 <- hwfiesdat
  p<-vector()
  factorspred <- matrix(nrow = nf,ncol = nrow(predicc))
  resppred <- matrix(nrow = nrow(predicc),ncol = 96)
  for(i in nrow(datos):363){
    
    factores<-estTSF.ML(datos2,nf,normalize=F,maxit=30000)
    fmodel<-factors(factores)
    serief1ts <- ts(fmodel)
    ##Mejor modelo con const.
    varf1 <- VAR(serief1ts,p=10, type="const",exogen = as.matrix(cbind(dat=datdom2,fest=fest2,nad=nad2)))
    
    aa<-predict(varf1,dumvar = as.matrix(cbind(preddom[j],festiuspred[j],hwfiespred[j])),n.ahead = 1)
    
    f1<-aa$fcst$Factor.1[,1]
    f2<-aa$fcst$Factor.2[,1]
    f3<-aa$fcst$Factor.3[,1]
    f4<-aa$fcst$Factor.4[,1]
    f5<-aa$fcst$Factor.5[,1]
    
    fac <- t(matrix(c(f1,f2,f3,f4,f5),nrow=length(f1),ncol=5))
    factorspred[,j]<-fac
    p<-c(p,t(factores$loadings%*%factorspred[,j]))
    resppred[j,]<-t(factores$loadings%*%factorspred[,j])
    #print(j)
    datos2 <- rbind(datos2,predicc[j,])
    datdom2 <- c(datdom2,preddom[j])
    fest2 <- c(fest2,festiuspred[j])
    nad2 <- c(nad2,hwfiespred[j])
    par(mfrow=c(2,1))
    ##plot individual
    plot(ts(as.vector(t(datos2[-c(1:(nrow(datos2)-1)),])),freq=96),type="l",
         lty=2,col="blue",ylim=c(0,max(c(as.vector(t(datos2[-c(1:(nrow(datos2)-1)),])),as.vector(t(resppred[j,]))))))
    lines(ts(as.vector(t(resppred[j,])),freq=96))
    
    ##plot colectivo
    plot(ts(as.vector(t(datos2[-c(1:nrow(datos)),])),freq=96),type="l",lty=2,col="blue")
    lines(ts(as.vector(t(resppred)),freq=96))
    
    j<-j+1
    
  }
}


    })


})
```